### ISSUE TITLE
Saving projects

### ISSUE THREAD

**Issue by SantosXPC** [jfo8000/ScratchJr-Desktop#11]
The Windows version 32 runs very well without any glicth. But It's possible to save projects or export projects created in ScrJr? Even at the official iPad app or Android is very difficult to preserve students projects as evidence. Thanks.

**Comment by jfo8000** [comment]
Sorry for the late reply.  

In the official ipad/android app the best you can do is "share".    Tap the top right of your project screen on the yellow polygon that just looks like a bent over piece of paper.  You will be given some sharing options for your device. 

In the desktop version...

The way the projects work is they're stored in an internal database.   In the community version we have made it possible to copy the entire database out.  

**Reloading Saved Projects**

For classroom use, sometimes it is handy to pre-configure a set of projects. All of the projects all save into the same Documents/ScratchJR/scratchjr.sqllite file. To set up projects beforehand, you can make a backup copy of this file. 

Here's how.

- Make starter projects for your class - set up Scratch Jr with the projects you want everyone to use.
- Open up the ScratchJR folder inside of Documents
- Copy the scratchjr.sqllite file to scratchjr.sqllite.restore
- Re-open ScratchJR for desktop.

After completing, there will be a menu option for restoring the projects. This will reset all the projects back to a clean copy of your projects. This is handy for a shared classroom setting where you don't wish to save the work between students. 

Hope this helps!

**Comment by valeriu-leu** [comment]
I am building an exporter/importer here if anybody needed to export to mobile version and viceversa: https://gitlab.com/val.leu/scratchjr-importer-exporter/-/blob/main/README.md
