### ISSUE TITLE
How to export a project created?

### ISSUE THREAD

**Issue by prashanthi357** [jfo8000/ScratchJr-Desktop#29]
Is there no way to export a project rather than sqllite file. please help?

Thanks,
Prashanthi

**Comment by prashanthi357** [comment]
Does anyone know how to export a project created? Please help.

**Comment by shabysheik** [comment]
I reckon you could go find scratchjr.sqllite and just copy the parent folder  ScratchJR to wherever you wanted it to go to. 

For me it is here:
C:\Users\shaby\OneDrive\Documents\ScratchJR

I copied that folder, went to a new computer and pasted it in after installing scratch. It worked a charm and the new machine now has the scratch files on it. I know this is using the sqllite file, but it is pretty easy to do...

**Comment by jfo8000** [comment]
Agree - at the moment you have to export the whole lot.  The original app has some limited project sharing capabilities by tapping on the corner of your project - but we weren't able to implement it without adding a feature to the app, which would have caused problems with the licensing. 

![image](https://user-images.githubusercontent.com/16273166/84116427-2f50b200-aa73-11ea-8c86-5795f9958b66.png)

On iPad/Android tapping that corner kinda lets you share a project between devices, but I have never actually done it.
