### ISSUE TITLE
ScratchJR doesn't load Fedora

### ISSUE THREAD

**Issue by leonskb4** [jfo8000/ScratchJr-Desktop#39]
After install Scratch in a clean fedora installation, Scratch doesn't load with error message:

(ScratchJr:5986): Pango-ERROR **: 21:10:46.280: Harfbuzz version too old (1.4.2)

**Comment by jfo8000** [comment]
Might try building from source and then upgrading the electron inside it?

**Comment by leonskb4** [comment]
when I update the dependencies, the activity is opened with no actions and without image or color background.

If you could help me I can make a PR with the updated libraries

![Captura de pantalla de 2020-07-16 08-49-26](https://user-images.githubusercontent.com/16105497/87679297-a39d0600-c741-11ea-8a98-7f8523764715.png)
![Captura de pantalla de 2020-07-16 08-52-33](https://user-images.githubusercontent.com/16105497/87679365-b4e61280-c741-11ea-8544-6917004dc851.png)

**Comment by leonskb4** [comment]
I can use with new libraries. I keep the versions of localization and sql.js and I update main.js

![Captura de pantalla de 2020-07-16 09-23-15](https://user-images.githubusercontent.com/16105497/87682883-fe386100-c745-11ea-93be-b47a9cfe8bc5.png)

Let me know if you want the pull request (Y)

**Comment by ShibaPonPon** [comment]
Any help on making it work ? I use Linux Mint 20 and have the same problem

**Comment by leonskb4** [comment]
I build this compressed [file](https://mega.nz/file/M9pyGCbb#GbT-P6nt33V6ra80A2nybWLq8ikgT5IcVpndK2hF1D4)
are only the executable files, you could try if work for you
